version: 1.0.0-{build}
configuration:
- Release
- Debug
platform:
- Any CPU
os: Visual Studio 2015
branches:
  only:
    - master
install:
 - ps: |
     Add-Type -AssemblyName System.IO.Compression.FileSystem
            (new-object System.Net.WebClient).DownloadFile(
              'https://github.com/dokan-dev/dokany/releases/download/v1.0.0-RC1/DokanSetup.exe',
              'C:\projects\dokan-dotnet\DokanSetup.exe'
            )
 - cmd: |
     C:\projects\dokan-dotnet\DokanSetup.exe /quiet
     copy "C:\Program Files\Dokan\Dokan Library-1.0.0\dokan1.dll" "C:\Windows\System32" 
     copy "C:\Program Files\Dokan\Dokan Library-1.0.0\x86\dokan1.dll" "C:\Windows\SysWOW64"

before_build:
  - nuget restore
build:
  project: DokanNet.sln
  verbosity: minimal
test:
  categories:
    except:
      - Manual
      - Timing
